export const COUNTRIES = [
  'O‘zbekiston',
  'Afg‘oniston',
  'Albaniya',
  'Jazoir',
  'Andorra',
  'Angola',
  'Antigua va Barbuda',
  'Argentina',
  'Armaniston',
  'Avstraliya',
  'Avstriya',
  'Ozarbayjon',
  'Bagama orollari',
  'Bahrayn',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgiya',
  'Beliz',
  'Benin',
  'Butan',
  'Boliviya',
  'Bosniya va Gertsegovina',
  'Botsvana',
  'Braziliya',
  'Bruney',
  'Bolgariya',
  'Burkina-Faso',
  'Burundi',
  'Kabo-Verde',
  'Kambodja',
  'Kamerun',
  'Kanada',
  'Markaziy Afrika Respublikasi',
  'Chad',
  'Chili',
  'Xitoy',
  'Kolumbiya',
  'Komor orollari',
  'Kongo',
  'Kosta-Rika',
  'Xorvatiya',
  'Kuba',
  'Kipr',
  'Chexiya',
  'Kongo Demokratik Respublikasi',
  'Daniya',
  'Jibuti',
  'Dominika',
  'Dominikan Respublikasi',
  'Ekvador',
  'Misr',
  'Salvador',
  'Ekvatorial Gvineya',
  'Eritreya',
  'Estoniya',
  'Eswatini',
  'Efiopiya',
  'Fiji',
  'Finlandiya',
  'Fransiya',
  'Gabon',
  'Gambiya',
  'Gruziya',
  'Germaniya',
  'Gana',
  'Gretsiya',
  'Grenada',
  'Gvatemala',
  'Gvineya',
  'Gvineya-Bisau',
  'Gayana',
  'Gaiti',
  'Gonduras',
  'Vengriya',
  'Islandiya',
  'Hindiston',
  'Indoneziya',
  'Eron',
  'Iroq',
  'Irlandiya',
  'Isroil',
  'Italiya',
  'Yamayka',
  'Yaponiya',
  'Iordaniya',
  'Qozog‘iston',
  'Keniya',
  'Kiribati',
  'Koreya Xalq Demokratik Respublikasi',
  'Koreya Respublikasi',
  'Quvayt',
  'Qirg‘iziston',
  'Laos',
  'Latviya',
  'Livan',
  'Lesoto',
  'Liberiya',
  'Liviya',
  'Lixtenstein',
  'Litva',
  'Lyuksemburg',
  'Madagaskar',
  'Malavi',
  'Malayziya',
  'Maldiv orollari',
  'Mali',
  'Malta',
  'Marshall orollari',
  'Mavritaniya',
  'Mavrikiy',
  'Meksika',
  'Mikroneziya',
  'Moldova',
  'Monako',
  'Mongoliya',
  'Chernogoriya',
  'Marokash',
  'Mozambik',
  'Myanma',
  'Namibiya',
  'Nauru',
  'Nepal',
  'Niderlandiya',
  'Yangi Zelandiya',
  'Nikaragua',
  'Niger',
  'Nigeriya',
  'Shimoliy Makedoniya',
  'Norvegiya',
  'Ummon',
  'Pokiston',
  'Palau',
  'Panama',
  'Papua — Yangi Gvineya',
  'Paragvay',
  'Peru',
  'Filippin',
  'Polsha',
  'Portugaliya',
  'Qatar',
  'Ruminiya',
  'Rossiya',
  'Ruanda',
  'Sent-Kits va Nevis',
  'Sent-Lyusiya',
  'Sent-Vinsent va Grenadinlar',
  'Samoa',
  'San-Marino',
  'San-Tome va Prinsipi',
  'Saudiya Arabistoni',
  'Senegal',
  'Serbiya',
  'Seyshel orollari',
  'Syerra-Leone',
  'Singapur',
  'Slovakiya',
  'Sloveniya',
  'Solomon orollari',
  'Somali',
  'Janubiy Afrika Respublikasi',
  'Janubiy Sudan',
  'Ispaniya',
  'Shri-Lanka',
  'Sudan',
  'Surinam',
  'Shvetsiya',
  'Shveytsariya',
  'Suriya',
  'Tojikiston',
  'Tanzaniya',
  'Tailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad va Tobago',
  'Tunis',
  'Turkiya',
  'Turkmaniston',
  'Tuvalu',
  'Uganda',
  'Ukraina',
  'Birlashgan Arab Amirliklari',
  'Buyuk Britaniya',
  'Amerika Qo‘shma Shtatlari',
  'Urugvay',
  'Vanuatu',
  'Vatikan',
  'Venesuela',
  'Vyetnam',
  'Yaman',
  'Zambiya',
  'Zimbabve',
  'Boshqa',
]
