export const API_TAGS = {
  USER: 'User',
  AUTH: 'Auth',
  STRUCTURE: 'Structure',
  COMMISSION: 'Commission',
  DASHBOARD: 'Dashboard',
  PURCHASE_REQUEST: 'PurchaseRequest',
  PURCHASE_REQUEST_SESSION: 'PurchaseRequestSession',
  TRANSFER: 'Transfer',
  WAREHOUSE_DISPATCH: 'WarehouseDispatch',
  WAREHOUSE_LOCATION: 'WarehouseLocation',
  WAREHOUSE_INVENTORY: 'WarehouseInventory',
  WAREHOUSE_EXPENSE: 'WarehouseExpense',
  WAREHOUSE_FIXED_ASSET: 'WarehouseFixedAsset',
  STOCKTAKE: 'Stocktake',
  NOTIFICATION: 'Notification',
  CHAT: 'Chat',
  PRODUCT: 'Product',
  WAREHOUSE_IMPORT_SESSION: 'WarehouseImportSession',
  WAREHOUSE_IMPORT: 'WarehouseImport',
  MEASUREMENT_UNIT: 'MeasurementUnit',
  TASK: 'Task',
}
