export { MeningOmborimPage } from './MeningOmborimPage'
export { BoshqaOmborlarPage } from './BoshqaOmborlarPage'
export { ChiqimQilishPage } from './ChiqimQilishPage'
export { ChiqimTarixiPage } from './ChiqimTarixiPage'
export { AsosiyVositalarPage } from './AsosiyVositalarPage'
